export const defaultVoiceList = [
  {
    Name: "zh-CN-XiaoxiaoNeural",
    Gender: "Female",
    ContentCategories: ["News", "Novel"],
    VoicePersonalities: ["Warm"],
    Engine: "edge",
  },
  {
    Name: "zh-CN-XiaoyiNeural",
    Gender: "Female",
    ContentCategories: ["Cartoon", "Novel"],
    VoicePersonalities: ["Lively"],
    Engine: "edge",
  },
  {
    Name: "zh-CN-YunjianNeural",
    Gender: "Male",
    ContentCategories: ["Sports", "Novel"],
    VoicePersonalities: ["Passion"],
    Engine: "edge",
  },
  {
    Name: "zh-CN-YunxiNeural",
    Gender: "Male",
    ContentCategories: ["Novel"],
    VoicePersonalities: ["Lively", "Sunshine"],
    Engine: "edge",
  },
  {
    Name: "zh-CN-YunxiaNeural",
    Gender: "Male",
    ContentCategories: ["Cartoon", "Novel"],
    VoicePersonalities: ["Cute"],
    Engine: "edge",
  },
  {
    Name: "zh-CN-YunyangNeural",
    Gender: "Male",
    ContentCategories: ["News"],
    VoicePersonalities: ["Professional", "Reliable"],
    Engine: "edge",
  },
  {
    Name: "zh-CN-liaoning-XiaobeiNeural",
    Gender: "Female",
    ContentCategories: ["Dialect"],
    VoicePersonalities: ["Humorous"],
    Engine: "edge",
  },
  {
    Name: "zh-CN-shaanxi-XiaoniNeural",
    Gender: "Female",
    ContentCategories: ["Dialect"],
    VoicePersonalities: ["Bright"],
    Engine: "edge",
  },
  {
    Name: "zh-HK-HiuGaaiNeural",
    Gender: "Female",
    ContentCategories: ["General"],
    VoicePersonalities: ["Friendly", "Positive"],
    Engine: "edge",
  },
  {
    Name: "zh-HK-HiuMaanNeural",
    Gender: "Female",
    ContentCategories: ["General"],
    VoicePersonalities: ["Friendly", "Positive"],
    Engine: "edge",
  },
  {
    Name: "zh-HK-WanLungNeural",
    Gender: "Male",
    ContentCategories: ["General"],
    VoicePersonalities: ["Friendly", "Positive"],
    Engine: "edge",
  },
  {
    Name: "zh-TW-HsiaoChenNeural",
    Gender: "Female",
    ContentCategories: ["General"],
    VoicePersonalities: ["Friendly", "Positive"],
    Engine: "edge",
  },
  {
    Name: "zh-TW-HsiaoYuNeural",
    Gender: "Female",
    ContentCategories: ["General"],
    VoicePersonalities: ["Friendly", "Positive"],
    Engine: "edge",
  },
  {
    Name: "zh-TW-YunJheNeural",
    Gender: "Male",
    ContentCategories: ["General"],
    VoicePersonalities: ["Friendly", "Positive"],
    Engine: "edge",
  },
  {
    Name: "zh-CN-XiaochenNeural",
    Gender: "Female",
    ContentCategories: ["Novel", "Cartoon"],
    VoicePersonalities: ["Lively", "Bright"],
    Engine: "azure",
  },
  {
    Name: "zh-CN-XiaohanNeural",
    Gender: "Female",
    ContentCategories: ["Novel", "News"],
    VoicePersonalities: ["Warm", "Calm"],
    Engine: "azure",
  },
  {
    Name: "zh-CN-XiaomengNeural",
    Gender: "Female",
    ContentCategories: ["Novel", "Cartoon"],
    VoicePersonalities: ["Cute", "Sweet"],
    Engine: "azure",
  },
  {
    Name: "zh-CN-XiaoruNeural",
    Gender: "Female",
    ContentCategories: ["Novel", "General"],
    VoicePersonalities: ["Warm", "Gentle"],
    Engine: "azure",
  },
  {
    Name: "zh-CN-XiaoshuangNeural",
    Gender: "Female",
    ContentCategories: ["Novel", "Cartoon"],
    VoicePersonalities: ["Cute", "Lively"],
    Engine: "azure",
  },
  {
    Name: "zh-CN-XiaoxuanNeural",
    Gender: "Female",
    ContentCategories: ["Novel", "News"],
    VoicePersonalities: ["Professional", "Calm"],
    Engine: "azure",
  },
  {
    Name: "zh-CN-XiaoyuNeural",
    Gender: "Female",
    ContentCategories: ["Novel", "General"],
    VoicePersonalities: ["Warm", "Gentle"],
    Engine: "azure",
  },
  {
    Name: "zh-CN-YunfengNeural",
    Gender: "Male",
    ContentCategories: ["Novel", "News"],
    VoicePersonalities: ["Steady", "Reliable"],
    Engine: "azure",
  },
  {
    Name: "zh-CN-YunhaoNeural",
    Gender: "Male",
    ContentCategories: ["Novel", "General"],
    VoicePersonalities: ["Warm", "Magnetic"],
    Engine: "azure",
  },
  {
    Name: "zh-CN-YunjieNeural",
    Gender: "Male",
    ContentCategories: ["Novel", "General"],
    VoicePersonalities: ["Steady"],
    Engine: "azure",
  },
  {
    Name: "zh-CN-YunzeNeural",
    Gender: "Male",
    ContentCategories: ["Novel", "General"],
    VoicePersonalities: ["Warm", "Gentle"],
    Engine: "azure",
  },
  {
    Name: "zh-CN-sichuan-XiaoyaNeural",
    Gender: "Female",
    ContentCategories: ["Dialect"],
    VoicePersonalities: ["Lively"],
    Engine: "azure",
  },
  {
    Name: "alloy",
    Gender: "Male",
    ContentCategories: ["General"],
    VoicePersonalities: ["Friendly"],
    Engine: "openai",
  },
  {
    Name: "echo",
    Gender: "Male",
    ContentCategories: ["General"],
    VoicePersonalities: ["Warm"],
    Engine: "openai",
  },
  {
    Name: "fable",
    Gender: "Male",
    ContentCategories: ["General"],
    VoicePersonalities: ["Friendly"],
    Engine: "openai",
  },
  {
    Name: "onyx",
    Gender: "Male",
    ContentCategories: ["General"],
    VoicePersonalities: ["Steady"],
    Engine: "openai",
  },
  {
    Name: "nova",
    Gender: "Female",
    ContentCategories: ["General"],
    VoicePersonalities: ["Bright"],
    Engine: "openai",
  },
  {
    Name: "shimmer",
    Gender: "Female",
    ContentCategories: ["General"],
    VoicePersonalities: ["Professional"],
    Engine: "openai",
  },
];

export const previewTextSelect = {
  'zh-CN': '这是一段测试文本，用于试听语音效果。你，听说过我的故事？',
  'en-US': 'This is a test text for testing the voice effect. Have you heard my story?',
  'en-GB': 'This is a test text for testing the voice effect. Have you heard my story?',
  'en-AU': 'This is a test text for testing the voice effect. Have you heard my story?',
  'en-CA': 'This is a test text for testing the voice effect. Have you heard my story?',
};
